apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: yxo88lox2-python
  janus-idp.io/tekton: yxo88lox2-python
  backstage.io/kubernetes-id: yxo88lox2-python
  backstage.io/kubernetes-namespace: tssc-app 
  app.kubernetes.io/part-of: yxo88lox2-python
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
